### ISSUE TITLE
Porting to VSCode?

### ISSUE THREAD

**Issue by XMA2l** [VBAndCs/Vazor#13]
Hey, just stumbled upon your very impressive project. 
Do you think this could be ported to VSCode so it could be used portably + on OSX and Linux? 
It would create a lot of possibilities! 
Would this be a lot of work?

**Comment by InteXX** [comment]
FYI there's no need to port.

It'll run in any environment that .NET 6 supports, which includes OSX and Linux (even RPi). You'll have to wire up Kestrel, yes, but that's a walk in the park.

**Comment by VBAndCs** [comment]
Welcome @XMA2l 
I agree with @InteXX as Vazor is a dotnet standard library, and you can reference it's NuGet from any .NET 6 project on VSCode. But, you are also right, as the Vazor extension which installs the project templates and the auto completion support is written for VS.NET. I can publish the source of the auto-completion code and the templates, so you can use them to create a VSCode extension if you want. Such extension uses JS and TS and I have no clue about the VSCode environment.

**Comment by InteXX** [comment]
@VBAndCs 

> I can publish the source of the auto-completion code and the templates

That's actually not a bad idea.

**Comment by VBAndCs** [comment]
@InteXX @XMA2l 
Here is the source of VazorEx:
https://github.com/VBAndCs/Vazor/tree/master/VazorEx

**Comment by InteXX** [comment]
@VBAndCs 

Looks good, thanks.

**Comment by XMA2l** [comment]
@VBAndCs

Thank you very much, could take a bit of time until i look through this though.
