### ISSUE TITLE
Vazor assembly in ~/wwwroot/lib

### ISSUE THREAD

**Issue by InteXX** [VBAndCs/Vazor#18]
I see there's a copy of `Vazor.dll` under `~/wwwroot/lib/Vazor`. This is unexpected.

1. Could you discuss why this is necessary?
2. What functionality does it provide in that location?
3. What's the difference between that version and the version under `bin\*`?

**Comment by VBAndCs** [comment]
I don't remember :)

Maybe it is copied by mistake while I am copying some other components, or I was trying something. Delete it and if everything works fine on the web server, then it is useless.



________________________________
From: Jeff Bowman ***@***.***>
Sent: Wednesday, January 31, 2024 1:24 AM
To: VBAndCs/Vazor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/Vazor] Vazor assembly in ~/wwwroot/lib (Issue #18)


I see there's a copy of Vazor.dll under ~/wwwroot/lib/Vazor. This is unexpected.

  1.  Could you discuss why this is necessary?
  2.  What functionality does it provide in that location?
  3.  What's the difference between that version and the version under bin\*?

**Comment by InteXX** [comment]
> I don't remember

I know the feeling ;-)

All seems to be well without it.
