### ISSUE TITLE
Else/ElseIf for <z /> tag conditions?

### ISSUE THREAD

**Issue by InteXX** [VBAndCs/Vazor#19]
I'm trying to do something like this:
```
<z:if condition="Sky.Today = Blue">
<z:else>
</z:if>
```
...but that produces a compiler error.

I tried this:
```
<z:else/>
```
...but the markup following that instruction wasn't sent to the browser.

I'm curious: does ZML support conditional branching like this?

**Comment by VBAndCs** [comment]
Xml is a tree of elements. The If tag should be written like this:

```

  <z:if condition=<%= "a <> 3 andalso b == 5" %>>

     <z:then>

         <p>test 1</p>

     </z:then>

     <z:else>

         <p>test 2</p>

     </z:else>

  </z:if>

```

________________________________
From: Jeff Bowman ***@***.***>
Sent: Thursday, February 22, 2024 10:05 PM
To: VBAndCs/Vazor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/Vazor] Else/ElseIf for <z /> tag conditions? (Issue #19)


I'm trying to do something like this:

<z:if condition="Sky.Today = Blue">
<z:else>
</z:if>


...but that produces a compiler error.

I tried this:

<z:else/>


...but the markup following that instruction wasn't sent to the browser.

I'm curious: does ZML support conditional branching like this?

**Comment by InteXX** [comment]
That works, thanks.
