### ISSUE TITLE
Vasor Upgrade to .net core 3 rc1

### ISSUE THREAD

**Issue by Sharaf-Mansour** [VBAndCs/Vazor#2]
Thanks for your Amazing help for the .NET and VB Community!
I have always dreamed of writing my Web Logic in VB Code and be able to compile it into WA.
But Could you please Upgrade your Project reference to the Latest Version of .NET Core 3 For new syntax support!
Thanks again for your great work and Looking forward for your Amazing projects!

**Comment by Sharaf-Mansour** [comment]
Also I think Using the VBHTML instead of CSHTML would be easier and better than using ZML but if only Microsoft Gave it enough Love and Support :(

**Comment by VBAndCs** [comment]
@Sharaf-Mansour 
Thanks for your support. Unfortunately I didn't get notification about posted issues in this repo (and don't know why!).
I updated Vazor to .NET Core 3.1. (Sorry for being late).
And in a few minutes I will publish the project template for this version.
