### ISSUE TITLE
VB 2019 AbstractVbXmlCompletionProvider TypeInitializationException

### ISSUE THREAD

**Issue by hlizard** [VBAndCs/Vazor#3]
https://developercommunity2.visualstudio.com/t/VB-2019-AbstractVbXmlCompletionProvider-/1297510?entry=myfeedback

**Comment by VBAndCs** [comment]
@hlizard 
Sorry, I didn't get any notification about this issue. Can you please post the issue here in English, providing some info about the VS version and windows version you are using?
Thanks.

**Comment by VBAndCs** [comment]
@hlizard 
https://marketplace.visualstudio.com/items?itemName=ModernVBNET.Vazor
