### ISSUE TITLE
Can't install on VS 2022

### ISSUE THREAD

**Issue by InteXX** [VBAndCs/Vazor#4]
An attempt to install on Visual Studio 2022 results in this message:

![image](https://user-images.githubusercontent.com/10966749/159170313-551c59df-b0df-4ad2-81e6-b8ae4a64a2be.png)

Is VS 2022 support a possibility?

A workaround:

1. Install VS 2019
2. Install the extension
3. Create a new Vazor project
4. Copy the project to a saved templates folder
5. Uninstall VS 2019

**Comment by VBAndCs** [comment]
It works fine for me:
VS2022 Community on Win 10 x64.
Did you use the extenstion manager from VS?
![image](https://user-images.githubusercontent.com/48354902/159171810-ca28df81-3f1a-44d8-8081-f67145f60c61.png)

**Comment by InteXX** [comment]
OK, that works. I was trying the install from the command line.

It looks like we lose Hot Reload, but if that's the worst of it we're in high cotton. That always felt clunky to me anyway. Not sure why they invested so much time in it.

Damn fine job on this, Mohammad. Good work.
