### ISSUE TITLE
gRPC error on build

### ISSUE THREAD

**Issue by InteXX** [VBAndCs/Vazor#6]
Do you have any idea how I might suppress a build error I'm getting when I add gRPC to my Vazor project?

Here's the error:

> Google.Protobuf.Tools proto compilation is only supported by default in a C# project

However, I'm not doing proto compilation in this project. The codegen project is a C# project, which I'm referencing in my Vazor project. Apparently the compiler isn't smart enough to figure that out.

Here's the relevant snippet from the `Google.Protobuf.Tools.Targets` file:

```
<!-- Check configuration sanity before build. -->
<Target Name="_Protobuf_SanityCheck" BeforeTargets="PrepareForBuild">
  <Error
    Condition=" '$(Protobuf_ProjectSupported)' != 'true' "
    Text="Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj)" />
</Target>
```

This started when I added the `Grpc.AspNetCore` package, so I could do this in `Startup.vb`:

```
Services.AddGrpc
```

I tried commenting out the `<Error />` element, and that works, but it's a hack—and a pretty lousy one at that.

To your knowledge, is there a dignified way to suppress this error so my project can build, without my having to alter the targets file?

**Comment by VBAndCs** [comment]
I didn't use gRPC b4, but it I gusee you are using it in the vazor project somehow. Referencing a project means refenencing a dll which is language agnostic. So, check vazor project again for a forgotten gRPc ref.

**Comment by InteXX** [comment]
In order to have gRPC listen on the same port as the website, we have to add a `Services.UseGrpc()` call. The package that contains that extension method is `Grpc.AspNetCore`, which in turn has a dependent package `Grpc.Tools`.

`Grpc.Tools` contains the targets file with the error, so because of the above hierarchy it comes along for the ride. It doesn't care that I'm not doing codegen in this project; all it cares about is that it's installed in a VB.NET project—and it objects.

I'm not familiar enough with MSBuild and compilation targets to know how to suppress the error gracefully, so for now it looks like we're stuck with commenting out the `<Error />` element.

**Comment by InteXX** [comment]
Here's a repro project: https://github.com/InteXX/vazor-grpc

Build the VazorMVC1 project and you'll see the error.

**Comment by InteXX** [comment]
This isn't directly a Vazor issue, so I'll close.

**Comment by InteXX** [comment]
FYI I'm giving up on gRPC; turns out it's [not going to work](https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0#supported-aspnet-core-servers) in my situation.
